In [1]:
#import pandas to read in the excel file
import pandas as pd

### Identify Duplicate

Procedure code
 
1.       Sort the data by all of the variables (denoted hereafter as X)
a.       It does not matter which order the variables are sorted in.
2.       Create two new variables eqn and eqsize
a.       For the first case set eqn to 1
3.       Test for equality between each case and the one that precedes it [X=lag(X)]
a.       If X =lag(X) then eqn=lag(eqn)+1
b.       If X /=lag(X) then eqn=1
4.       Reverse sort the data
5.       For each case test if eqn<lag(eqn)
a.       If eqn < lag(eqn) then  eqsize=lag(eqsize)
b.       If eqn >= lag(eqn) then eqsize=eqn

In [2]:
#new sort funtion that sorts in ascending order
#mylist - is the list sort, this should be empty after sorting
#emptylist - this would be filled with the sorted list, len(emptylist) == len(mylist-before sorting)
def sorting(mylist, emptylist):
    while mylist:
        minimum = mylist[0]  #start with the first case
        for x in mylist: 
            if x < minimum:
                minimum = x #change the minimum value if any x is less than the first case
                #ind = mylist.index(minimum)
        emptylist.append(minimum) #append the minimum to emptylist
        mylist.remove(minimum) #remove the minimum from the original list

In [3]:
data = pd.read_csv('data.csv') #read in data using pandas

In [4]:
test = data.T.to_dict('list') #transpose this dataframe and turn into a dictonary

In [5]:
gender = [] #make it into the a list, append by gender

In [6]:
for key, value in test.items():
    if value[9] == 1: #append gender == 1
        gender.append(value)
    if value[9] == 2: #then gender == 2
        gender.append(value)

In [7]:
gender_sorted = [] #create an empty list to put in the sorted cases
sorting(gender, gender_sorted) #use the sorting function created

In [8]:
q = gender_sorted #assign to q for ease in refereing to

In [9]:
len(q) #check length is as expected

29913

In [10]:
a = 0 #index of first case (X)
b = 1 #index of lag(X)

In [11]:
q[a] = q[a], 1 #create a second variable (EQN) for X

In [12]:
#Test for equality between each case and the lag
try: 
    while q:
        if q[a][0] == q[b]: #if the first case is same as its lag
            #x = int(q[a][1]) + 1
            q[b] = q[b], int(q[a][1]) + 1 #make the EQN of the lag == EQN of the first case and continue
            #if above is satisfied add 1 to a and b
            a+=1 
            b+=1
        else:
            q[b] = q[b], 1 #if above is not satisfied, make the EQN of the lag == 1
            #if above is satisfied add 1 to a and b
            a+=1
            b+=1
except IndexError: #catch index error
    print ("Finished - All Duplicates Indentified")

Finished - All Duplicates Indentified

In [13]:
#reverse sort: did this by appending starting from the last index
new = [] #new list to append to
ind = len(q) - 1 #the index is the len of old list(q) minus 1
for x in q:
    new.append(list(q[ind]))
    ind-=1

In [14]:
q = new #reassign to q, again fo ease in referring to

In [15]:
#create a new variable EQSIZE to assign duplicate number
q[0] = [q[0][0], q[0][1], q[0][1]] #for the first case this is equal to EQN

In [16]:
a = 0 #index of first case (X)
b = 1 #index of lag(X)

In [17]:
try: 
    while q:
        if q[b][1] < q[a][1]: #if EQN of the first case is more than its lag,
            q[b] = [q[b][0],q[b][1],q[a][2]] #make lag EQSIZE == first case EQSIZE
            #if above is satisfied add 1 to a and b
            a+=1
            b+=1
        else:
            #q[b][1] >= q[a][1]
            q[b] = [q[b][0],q[b][1],q[b][1]] #else make lag EQSIZE == lag EQN
            #if above is satisfied add 1 to a and b
            a+=1
            b+=1
except IndexError:
    print ("Finished - EQSIZE IDENTIFIED")

Finished - EQSIZE IDENTIFIED

In [18]:
df = pd.DataFrame(q) #make q a dataframe
a = list(df.pop(0)) #drop the first column (which is the original data)
df1 = pd.DataFrame(a) #make the original data back into a dataframe
result = pd.concat([df1, df], axis=1, sort=False) #merge original data and the 2 new columns (EQN and EQSIZE)
#add the column names
result.columns = ['CARS', 'HHSPTYPE', 'TENURE', 'PERSINHH', 'ECONPRIM', 'ETHGROUP', 'LTILL', 
       'MSTATUS', 'OCCPATN', 'SEX', 'SOCLASS', 'SEGROUP', 'EQN', 'EQSIZE']

In [20]:
#view new data
result

,CARS,HHSPTYPE,TENURE,PERSINHH,ECONPRIM,ETHGROUP,LTILL,MSTATUS,OCCPATN,SEX,SOCLASS,SEGROUP,EQN,EQSIZE
0,3,14,2,5,10,1,2,4,148,1,4,15,1,1
1,3,14,2,5,2,1,2,4,237,2,5,10,1,1
2,3,14,2,5,-9,1,2,1,-9,2,-9,-9,1,1
3,3,14,2,5,-9,1,2,1,-9,1,-9,-9,2,2
4,3,14,2,5,-9,1,2,1,-9,1,-9,-9,1,2
5,3,6,3,2,4,1,2,4,304,1,4,15,1,1
6,3,6,3,2,1,1,2,1,225,2,4,10,1,1
7,3,6,2,6,10,1,2,2,-9,2,-9,-9,1,1
8,3,6,2,6,7,1,2,1,-9,1,-9,-9,3,3
9,3,6,2,6,7,1,2,1,-9,1,-9,-9,2,3
10,3,6,2,6,7,1,2,1,-9,1,-9,-9,1,3
11,3,6,2,6,1,1,2,2,60,1,2,7,1,1
12,3,6,2,6,1,1,2,1,131,1,3,9,1,1
13,3,6,2,3,10,1,2,4,-9,2,-9,-9,1,1
14,3,6,2,3,3,1,2,4,36,1,2,3,1,1
15,3,6,2,3,-9,1,1,1,-9,2,-9,-9,1,1
16,3,6,1,3,10,1,2,2,-9,2,-9,-9,1,1
17,3,6,1,3,9,1,2,2,-9,1,-9,-9,1,1
18,3,6,1,3,2,1,2,1,238,2,5,10,1,1
19,3,5,5,1,3,1,2,4,358,1,8,20,1,1
20,3,5,2,4,4,1,2,2,313,1,4,15,1,1
21,3,5,2,4,3,1,2,3,36,2,2,3,1,1
22,3,5,2,4,1,1,2,1,357,1,6,14,1,1
23,3,5,2,4,1,1,2,1,127,2,3,9,1,1
24,3,5,1,1,9,1,2,5,36,1,2,4,1,1
25,3,4,7,3,5,1,2,1,206,1,4,12,1,1
26,3,4,7,3,2,10,2,1,227,2,5,10,1,1
27,3,4,7,3,1,1,2,1,206,1,4,12,1,1
28,3,4,6,1,1,1,2,1,179,1,4,12,1,1
29,3,4,2,5,2,1,2,2,93,2,2,7,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29883,0,1,1,1,9,1,2,5,-9,2,-9,-9,4,16
29884,0,1,1,1,9,1,2,5,-9,2,-9,-9,3,16
29885,0,1,1,1,9,1,2,5,-9,2,-9,-9,2,16
29886,0,1,1,1,9,1,2,5,-9,2,-9,-9,1,16
29887,0,1,1,1,9,1,2,4,-9,2,-9,-9,2,2
29888,0,1,1,1,9,1,2,4,-9,2,-9,-9,1,2
29889,0,1,1,1,9,1,2,2,-9,2,-9,-9,1,1
29890,0,1,1,1,9,1,2,1,-9,2,-9,-9,5,5
29891,0,1,1,1,9,1,2,1,-9,2,-9,-9,4,5
29892,0,1,1,1,9,1,2,1,-9,2,-9,-9,3,5
29893,0,1,1,1,9,1,2,1,-9,2,-9,-9,2,5
29894,0,1,1,1,9,1,2,1,-9,2,-9,-9,1,5
29895,0,1,1,1,9,1,1,5,-9,2,-9,-9,12,12
29896,0,1,1,1,9,1,1,5,-9,2,-9,-9,11,12
29897,0,1,1,1,9,1,1,5,-9,2,-9,-9,10,12
29898,0,1,1,1,9,1,1,5,-9,2,-9,-9,9,12
29899,0,1,1,1,9,1,1,5,-9,2,-9,-9,8,12
29900,0,1,1,1,9,1,1,5,-9,2,-9,-9,7,12
29901,0,1,1,1,9,1,1,5,-9,2,-9,-9,6,12
29902,0,1,1,1,9,1,1,5,-9,2,-9,-9,5,12
29903,0,1,1,1,9,1,1,5,-9,2,-9,-9,4,12
29904,0,1,1,1,9,1,1,5,-9,2,-9,-9,3,12
29905,0,1,1,1,9,1,1,5,-9,2,-9,-9,2,12
29906,0,1,1,1,9,1,1,5,-9,2,-9,-9,1,12
29907,0,1,1,1,9,1,1,5,-9,1,-9,-9,1,1
29908,0,1,1,1,9,1,1,1,-9,2,-9,-9,3,3
29909,0,1,1,1,9,1,1,1,-9,2,-9,-9,2,3
29910,0,1,1,1,9,1,1,1,-9,2,-9,-9,1,3
29911,0,1,1,1,6,1,2,5,340,1,6,14,1,1
29912,0,1,1,1,2,1,2,5,355,2,6,14,1,1